### ISSUE TITLE
AppStoreUpdateChecker.py failure

### ISSUE THREAD

**Issue by apizz** [autopkg/nmcspadden-recipes#33]
Just wanted to report after recently updating our autopkg version to 2.0.2 and getting failures due to `urllib2`:

Ran our override: `autopkg run AppleConfigurator2.or.munki -vv`

which produced:
```
Processing AppleConfigurator2.or.munki...
WARNING: /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes/AppStoreApp/AppStoreUpdateChecker.py: No module named 'urllib2'
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 891, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes/AppStoreApp/AppStoreUpdateChecker.py", line 21, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 891, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
Failed.
Receipt written to /tmp/receipts/AppleConfigurator2.or-receipt-20200206-100144.plist

The following recipes failed:
    AppleConfigurator2.or.munki
        Unable to import 'AppStoreUpdateChecker', likely due to syntax or Python error.

Nothing downloaded, packaged or imported.
```

**Comment by apizz** [comment]
Reinstalling autopkg 1.4.1 does not produce this error.  Should have stated previously that this is running on a Mac mini on 10.14.6 with the latest munki components installed and AutoPkgr 1.5.2

**Comment by nmcspadden** [comment]
It has now been deleted :)
